#!/usr/bin/env python3
"""Prepare SQL files for JBrowse assembly and ATAC track registry import."""

from __future__ import annotations

import argparse
import csv
import json
import re
from pathlib import Path
from typing import Any


MANIFEST_COLUMNS = [
    "dataset",
    "project_id",
    "cell_line",
    "sample_id",
    "species_id",
    "assembly_name",
    "ref_name",
    "signal_bw_path",
    "peaks_path",
    "peaks_index_path",
    "summits_path",
    "summits_index_path",
    "track_meta_path",
    "assembly_meta_path",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate idempotent SQL imports for JBrowse registry tables."
    )
    parser.add_argument(
        "--assembly-meta",
        type=Path,
        required=True,
        help="assembly.meta.json generated by pipeline step 3.",
    )
    parser.add_argument(
        "--track-manifest",
        type=Path,
        required=False,
        help="Cell-line merged JBrowse track manifest TSV. Optional when --only-assembly is set.",
    )
    parser.add_argument(
        "--only-assembly",
        action="store_true",
        help="Only generate the assembly SQL; skip track and validation SQL.",
    )
    parser.add_argument(
        "--datasets",
        nargs="+",
        help="Optional dataset IDs to keep from the merged manifest for local testing.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        required=True,
        help="Directory where SQL files will be written.",
    )
    parser.add_argument(
        "--jbrowse-data-root",
        type=Path,
        help="Optional root used to read per-track track.meta.json for signal_source_mode.",
    )
    parser.add_argument(
        "--uri-prefix",
        default="/jbrowse-data/",
        help="Public URI prefix for track.meta.json and assembly.meta.json paths.",
    )
    parser.add_argument(
        "--big-data-uri-prefix",
        default="/icellomics/jbrowse-data/",
        help="Public URI prefix for big data files (signal.bw, peaks, summits).",
    )
    parser.add_argument(
        "--assembly-accession",
        default="",
        help="Optional assembly accession, for example GCA_000001405.29.",
    )
    parser.add_argument(
        "--assembly-key",
        default="",
        help="Optional stable assembly key. Default is species<id>_<assembly_name>.",
    )
    parser.add_argument(
        "--is-default",
        type=int,
        choices=(0, 1),
        default=1,
        help="Value for tb_genome_assembly_resource.is_default.",
    )
    parser.add_argument(
        "--refgenome-database",
        default="big_industry_cell_refgenome_ds0001",
        help="DS0001 database name.",
    )
    parser.add_argument(
        "--atac-database",
        default="big_industry_cell_atac_results_ds0005",
        help="DS0005 database name.",
    )
    return parser.parse_args()


def read_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8-sig") as handle:
        return json.load(handle)


def sql_string(value: Any) -> str:
    if value is None:
        return "NULL"
    text = str(value)
    if text == "":
        return "NULL"
    return "'" + text.replace("\\", "\\\\").replace("'", "''") + "'"


def sql_number(value: Any) -> str:
    if value is None or str(value).strip() == "":
        return "NULL"
    return str(int(value))


def normalize_uri_prefix(prefix: str) -> str:
    if not prefix:
        return "/"
    return prefix if prefix.endswith("/") else prefix + "/"


def to_uri(relative_or_uri: str, uri_prefix: str) -> str:
    text = (relative_or_uri or "").strip()
    if not text:
        return ""
    if text.startswith(("http://", "https://", "/")):
        return text
    return normalize_uri_prefix(uri_prefix) + text.lstrip("/")


def assembly_key_for(species_id: str, assembly_name: str, explicit_key: str) -> str:
    if explicit_key:
        return explicit_key
    normalized = re.sub(r"[^A-Za-z0-9]+", "_", assembly_name).strip("_").lower()
    return f"species{species_id}_{normalized}"


def filename_token(value: str) -> str:
    token = re.sub(r"[^A-Za-z0-9._-]+", "_", value.strip())
    token = token.strip("._-")
    return token or "unknown"


def single_value(rows: list[dict[str, str]], column: str) -> str:
    values = sorted({row[column] for row in rows if row[column]})
    if len(values) != 1:
        raise SystemExit(
            f"Expected exactly one {column} in the merged manifest, found: {values}"
        )
    return values[0]


def get_manifest_context(
    meta: dict[str, Any],
    rows: list[dict[str, str]],
) -> dict[str, str]:
    cell_line = single_value(rows, "cell_line")
    manifest_species_id = single_value(rows, "species_id")
    manifest_assembly_name = single_value(rows, "assembly_name")
    ref_name = single_value(rows, "ref_name")

    assembly_species_id = str(meta["species_id"])
    assembly_name = str(meta["assembly_name"])
    if manifest_species_id != assembly_species_id:
        raise SystemExit(
            "Manifest species_id does not match assembly.meta.json: "
            f"{manifest_species_id} != {assembly_species_id}"
        )
    if manifest_assembly_name != assembly_name:
        raise SystemExit(
            "Manifest assembly_name does not match assembly.meta.json: "
            f"{manifest_assembly_name} != {assembly_name}"
        )

    return {
        "cell_line": cell_line,
        "ref_name": ref_name,
        "species_id": assembly_species_id,
        "assembly_name": assembly_name,
    }


def build_assembly_output_tag(context: dict[str, str]) -> str:
    tokens = [
        filename_token(context["ref_name"]),
        f"species{filename_token(context['species_id'])}",
        filename_token(context["assembly_name"]),
    ]
    return ".".join(tokens)


def build_track_output_tag(context: dict[str, str]) -> str:
    tokens = [
        filename_token(context["cell_line"]),
        filename_token(context["ref_name"]),
        f"species{filename_token(context['species_id'])}",
        filename_token(context["assembly_name"]),
    ]
    return ".".join(tokens)


def write_assembly_sql(
    args: argparse.Namespace,
    meta: dict[str, Any],
    output_dir: Path,
    output_tag: str,
) -> Path:
    species_id = str(meta["species_id"])
    assembly_name = str(meta["assembly_name"])
    assembly_key = assembly_key_for(species_id, assembly_name, args.assembly_key)

    values = {
        "species_id": species_id,
        "assembly_name": assembly_name,
        "assembly_accession": args.assembly_accession,
        "assembly_key": assembly_key,
        "sequence_adapter": meta.get("sequence_adapter", "BgzipFastaAdapter"),
        "fasta_uri": to_uri(meta.get("sequence_uri", ""), args.big_data_uri_prefix),
        "fai_uri": to_uri(meta.get("fai_uri", ""), args.big_data_uri_prefix),
        "gzi_uri": to_uri(meta.get("gzi_uri", ""), args.big_data_uri_prefix),
        "annotation_adapter": meta.get("annotation_adapter", "GtfAdapter"),
        "gtf_uri": to_uri(meta.get("gtf_uri", ""), args.big_data_uri_prefix),
        "annotation_uri": to_uri(meta.get("annotation_uri", ""), args.big_data_uri_prefix),
        "annotation_index_uri": to_uri(
            meta.get("annotation_index_uri", ""), args.big_data_uri_prefix
        ),
        "chrom_sizes_uri": to_uri(meta.get("chrom_sizes_uri", ""), args.big_data_uri_prefix),
        "is_default": args.is_default,
    }

    sql = f"""USE `{args.refgenome_database}`;

INSERT INTO `tb_genome_assembly_resource` (
  `species_id`,
  `assembly_name`,
  `assembly_accession`,
  `assembly_key`,
  `sequence_adapter`,
  `fasta_uri`,
  `fai_uri`,
  `gzi_uri`,
  `annotation_adapter`,
  `gtf_uri`,
  `annotation_uri`,
  `annotation_index_uri`,
  `chrom_sizes_uri`,
  `is_default`,
  `updated_at`
) VALUES (
  {sql_number(values["species_id"])},
  {sql_string(values["assembly_name"])},
  {sql_string(values["assembly_accession"])},
  {sql_string(values["assembly_key"])},
  {sql_string(values["sequence_adapter"])},
  {sql_string(values["fasta_uri"])},
  {sql_string(values["fai_uri"])},
  {sql_string(values["gzi_uri"])},
  {sql_string(values["annotation_adapter"])},
  {sql_string(values["gtf_uri"])},
  {sql_string(values["annotation_uri"])},
  {sql_string(values["annotation_index_uri"])},
  {sql_string(values["chrom_sizes_uri"])},
  {sql_number(values["is_default"])},
  NOW()
)
ON DUPLICATE KEY UPDATE
  `assembly_accession` = VALUES(`assembly_accession`),
  `assembly_key` = VALUES(`assembly_key`),
  `sequence_adapter` = VALUES(`sequence_adapter`),
  `fasta_uri` = VALUES(`fasta_uri`),
  `fai_uri` = VALUES(`fai_uri`),
  `gzi_uri` = VALUES(`gzi_uri`),
  `annotation_adapter` = VALUES(`annotation_adapter`),
  `gtf_uri` = VALUES(`gtf_uri`),
  `annotation_uri` = VALUES(`annotation_uri`),
  `annotation_index_uri` = VALUES(`annotation_index_uri`),
  `chrom_sizes_uri` = VALUES(`chrom_sizes_uri`),
  `is_default` = VALUES(`is_default`),
  `updated_at` = NOW();
"""

    output_path = output_dir / f"import_jbrowse_assembly_resource.{output_tag}.sql"
    output_path.write_text(sql, encoding="utf-8")
    return output_path


def read_track_meta(row: dict[str, str], jbrowse_data_root: Path | None) -> dict[str, Any]:
    if jbrowse_data_root is None or not row.get("track_meta_path"):
        return {}
    path = jbrowse_data_root / row["track_meta_path"]
    if not path.is_file():
        return {}
    return read_json(path)


def read_manifest(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        if reader.fieldnames != MANIFEST_COLUMNS:
            raise SystemExit(
                f"Unexpected manifest header in {path}\n"
                f"Found:    {reader.fieldnames}\n"
                f"Expected: {MANIFEST_COLUMNS}"
            )
        return [
            {column: (row.get(column) or "").strip() for column in MANIFEST_COLUMNS}
            for row in reader
        ]


def filter_manifest_rows(
    rows: list[dict[str, str]],
    datasets: list[str] | None,
) -> list[dict[str, str]]:
    if not datasets:
        return rows

    keep = {item.strip() for item in datasets if item and item.strip()}
    filtered = [row for row in rows if row["dataset"] in keep]
    found = {row["dataset"] for row in filtered}
    missing = sorted(keep - found)
    if missing:
        raise SystemExit(f"Requested datasets were not found in the manifest: {missing}")
    return filtered


def build_track_insert(row: dict[str, str], track_meta: dict[str, Any], args: argparse.Namespace) -> str:
    source_project_dir = ""
    if row["project_id"] and row["cell_line"]:
        source_project_dir = f"{row['project_id']}_{row['cell_line']}"

    values = [
        sql_string(row["dataset"]),
        sql_string(row["cell_line"]),
        sql_string(row["project_id"]),
        sql_string(row["sample_id"]),
        sql_number(row["species_id"]),
        sql_string(row["assembly_name"]),
        sql_string(row["ref_name"]),
        sql_string(to_uri(row["signal_bw_path"], args.big_data_uri_prefix)),
        sql_string(to_uri(row["peaks_path"], args.big_data_uri_prefix)),
        sql_string(to_uri(row["peaks_index_path"], args.big_data_uri_prefix)),
        sql_string(to_uri(row["summits_path"], args.big_data_uri_prefix)),
        sql_string(to_uri(row["summits_index_path"], args.big_data_uri_prefix)),
        sql_string(to_uri(row["track_meta_path"], args.uri_prefix)),
        sql_string(to_uri(row["assembly_meta_path"], args.uri_prefix)),
        sql_string(track_meta.get("signal_mode", "")),
        sql_string(source_project_dir),
        "1",
        "NOW()",
    ]
    return "  (" + ", ".join(values) + ")"


def write_track_sql(
    args: argparse.Namespace,
    rows: list[dict[str, str]],
    output_dir: Path,
    output_tag: str,
) -> Path:
    inserts = []
    jbrowse_data_root = args.jbrowse_data_root.resolve() if args.jbrowse_data_root else None
    for row in rows:
        if not row["dataset"]:
            continue
        track_meta = read_track_meta(row, jbrowse_data_root)
        inserts.append(build_track_insert(row, track_meta, args))

    if not inserts:
        raise SystemExit("The merged track manifest contains no dataset rows.")

    inserts_str = ",\n".join(inserts)
    sql = f"""USE `{args.atac_database}`;

INSERT INTO `tb_atac_jbrowse_track` (
  `dataset`,
  `cell_line`,
  `project_id`,
  `sample_id`,
  `species_id`,
  `assembly_name`,
  `ref_name`,
  `signal_bw_uri`,
  `peak_uri`,
  `peak_index_uri`,
  `summit_uri`,
  `summit_index_uri`,
  `track_meta_uri`,
  `assembly_meta_uri`,
  `signal_source_mode`,
  `source_project_dir`,
  `is_active`,
  `updated_at`
) VALUES
{inserts_str}
ON DUPLICATE KEY UPDATE
  `cell_line` = VALUES(`cell_line`),
  `project_id` = VALUES(`project_id`),
  `sample_id` = VALUES(`sample_id`),
  `species_id` = VALUES(`species_id`),
  `assembly_name` = VALUES(`assembly_name`),
  `ref_name` = VALUES(`ref_name`),
  `signal_bw_uri` = VALUES(`signal_bw_uri`),
  `peak_uri` = VALUES(`peak_uri`),
  `peak_index_uri` = VALUES(`peak_index_uri`),
  `summit_uri` = VALUES(`summit_uri`),
  `summit_index_uri` = VALUES(`summit_index_uri`),
  `track_meta_uri` = VALUES(`track_meta_uri`),
  `assembly_meta_uri` = VALUES(`assembly_meta_uri`),
  `signal_source_mode` = VALUES(`signal_source_mode`),
  `source_project_dir` = VALUES(`source_project_dir`),
  `is_active` = VALUES(`is_active`),
  `updated_at` = NOW();
"""

    output_path = output_dir / f"import_atac_jbrowse_tracks.{output_tag}.sql"
    output_path.write_text(sql, encoding="utf-8")
    return output_path


def write_validation_sql(
    args: argparse.Namespace,
    output_dir: Path,
    output_tag: str,
    rows: list[dict[str, str]],
) -> Path:
    cell_line = single_value(rows, "cell_line")
    species_id = single_value(rows, "species_id")
    assembly_name = single_value(rows, "assembly_name")
    # DS0005 stores per-cell-line peak tables, e.g. tb_atac_peak_sk-br-3.
    peak_table = f"tb_atac_peak_{cell_line.lower()}"
    sql = f"""USE `{args.atac_database}`;

SELECT COUNT(*) AS active_browser_tracks
FROM `tb_atac_jbrowse_track`
WHERE `is_active` = 1
  AND `cell_line` = {sql_string(cell_line)}
  AND `species_id` = {sql_number(species_id)}
  AND `assembly_name` = {sql_string(assembly_name)};

SELECT t.`dataset`, t.`cell_line`
FROM `tb_atac_jbrowse_track` t
LEFT JOIN `{peak_table}` p
  ON p.`dataset` = t.`dataset`
WHERE t.`is_active` = 1
  AND t.`cell_line` = {sql_string(cell_line)}
  AND t.`species_id` = {sql_number(species_id)}
  AND t.`assembly_name` = {sql_string(assembly_name)}
  AND p.`dataset` IS NULL
GROUP BY t.`dataset`, t.`cell_line`;

SELECT `cell_line`, COUNT(*) AS track_count
FROM `tb_atac_jbrowse_track`
WHERE `is_active` = 1
  AND `cell_line` = {sql_string(cell_line)}
  AND `species_id` = {sql_number(species_id)}
  AND `assembly_name` = {sql_string(assembly_name)}
GROUP BY `cell_line`
ORDER BY `cell_line`;

USE `{args.refgenome_database}`;

SELECT `species_id`, `assembly_name`, `assembly_key`, `is_default`
FROM `tb_genome_assembly_resource`
WHERE `species_id` = {sql_number(species_id)}
  AND `assembly_name` = {sql_string(assembly_name)}
ORDER BY `species_id`, `assembly_name`;
"""
    output_path = output_dir / f"validate_jbrowse_registry_import.{output_tag}.sql"
    output_path.write_text(sql, encoding="utf-8")
    return output_path


def main() -> None:
    args = parse_args()
    output_dir = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    assembly_meta = read_json(args.assembly_meta)

    if args.track_manifest is None:
        if not args.only_assembly:
            raise SystemExit(
                "--track-manifest is required unless --only-assembly is set."
            )
        manifest_rows: list[dict[str, str]] = []
    else:
        manifest_rows = filter_manifest_rows(
            read_manifest(args.track_manifest), args.datasets
        )
        if not manifest_rows:
            raise SystemExit("The merged track manifest contains no dataset rows.")

    if manifest_rows:
        manifest_context = get_manifest_context(assembly_meta, manifest_rows)
    else:
        manifest_context = {
            "cell_line": "",
            "ref_name": str(assembly_meta.get("ref_name", "")),
            "species_id": str(assembly_meta["species_id"]),
            "assembly_name": str(assembly_meta["assembly_name"]),
        }

    assembly_output_tag = build_assembly_output_tag(manifest_context)
    assembly_sql = write_assembly_sql(args, assembly_meta, output_dir, assembly_output_tag)
    print(f"Assembly SQL written:   {assembly_sql}")
    print(f"Assembly output tag:    {assembly_output_tag}")

    if args.only_assembly:
        return

    track_output_tag = build_track_output_tag(manifest_context)
    track_sql = write_track_sql(args, manifest_rows, output_dir, track_output_tag)
    validation_sql = write_validation_sql(args, output_dir, track_output_tag, manifest_rows)
    print(f"Track SQL written:      {track_sql}")
    print(f"Validation SQL written: {validation_sql}")
    print(f"Track output tag:       {track_output_tag}")
    print(f"Track rows prepared:    {len(manifest_rows)}")


if __name__ == "__main__":
    main()
